# Generated by Django 3.2.3 on 2021-05-15 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emissora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'emissora',
            },
        ),
        migrations.CreateModel(
            name='Audiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_audiencia', models.DateTimeField(verbose_name='Data e Hora da Audiência')),
                ('emissora_audiencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.emissora', verbose_name='Emissora')),
            ],
            options={
                'db_table': 'audiencia',
            },
        ),
    ]
