# Generated by Django 3.2.3 on 2021-05-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencia',
            name='pontos_audiencia',
            field=models.IntegerField(null=True),
        ),
    ]
