# Generated by Django 3.2.3 on 2021-05-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210515_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissora',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
